version: '3.8'
services:
  movies:
    image: adityasinghio/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: adityasinghio/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: adityasinghio/paydth:latest
    ports:
      - "83:80"
    deploy:
      replicas : 3

  recharge:
    image: adityasinghio/payrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
