version: '3.8'
services:
  movies:
    image: adityasinghio/paymovies:latest
    ports:
      - "85:80"
    deploy:
      replicas: 3

  train:
    image: adityasinghio/paytrain:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3

  dth:
    image: adityasinghio/paydth:latest
    ports:
      - "87:80"
    deploy:
      replicas : 3

  recharge:
    image: adityasinghio/payrecharge:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3
